### ISSUE TITLE
Pythonpath : Best (?) Version of Python to use?

### ISSUE THREAD

**Issue by askpatrickw** [Josverl/micropython-stubber#12]
I can see in your example you are using Python3.6 as your baseline Python version:

`"python.pythonPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\python.exe",`

The MicroPython docs say its based on 3.4(which could be incorrect now) but I also know there's been additional features brought back into MicroPython from later Python releases. 

I'm just wondering why that specific version in your example and if there's some trigger we can use to know when to move forward.

Thanks,
-p

**Comment by Josverl** [comment]
hi Patrick,

I've been using different versions of python on my host and have found little differences between them thus far.
there are a few modules that have CPYTHON --> Micropython patches/conversions built into them, but ive never checked into the version specifics of these.

I've been wrangling to get some tests written in order be able to validate the generation and the use withouth too much manual effort, and that is something that would be needed in order to figure that part out.

to avoid confusion, ill see if i can remove that pythonpath from the .vscode environment
